name: infrastructure
description: The Infrastructure layer of the project.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.1.2

dependencies:
  domain:
    path: ../domain
  shared:
    path: ../shared

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
